name: Generate ACubed report
on: workflow_dispatch
jobs:
  build-report:
    name: Build report
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: ./
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: acubed-report
          path: ./main.pdf
  release-report:
    name: Download report
    runs-on: ubuntu-latest
    needs: build-report
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: acubed-report
    - name: Test artifact download
      run: ls -R
